# Site settings
author: Stephen Clark
promo: Student at Carnegie Mellon University
keywords: "Stephen Clark, sclark, sclarkio, developer, cmu, Carnegie Mellon, San Diego, La Jolla, MoneyThink, spring carnival"
intro: >
  I'm a young, aspiring developer just over six feet tall. While I can't sing or dance I do consider myself very skilled in developing solutions for solving challenging problems.

compress_html:
  clippings: all
  endings: all
