# Site settings
author: Stephen Clark
email: hello@sclark.io
promo: Student at Carnegie Mellon University
keywords: "Stephen Clark, sclark, sclarkio, developer, cmu, Carnegie Mellon, San Diego, La Jolla, MoneyThink, spring carnival"
intro: >
  I'm an aspiring Software Engineer interested in working on cutting edge technology and impactful projects. Through previous internships I have demonstrated my skills and potential, and I am excited to apply what I have learned to future opportunities.

compress_html:
  clippings: all
  endings: all
